export const DC_EDIT_SET_CAPACITY_MIN_POWER = 'dc_edit/SET_CAPACITY_MIN_POWER';
export const DC_EDIT_SET_CAPACITY_MIN_FLOOR_SPACE =
    'dc_edit/SET_CAPACITY_MIN_FLOOR_SPACE';
export const DC_EDIT_SET_CAPACITY_MAX_POWER = 'dc_edit/SET_CAPACITY_MAX_POWER';
export const DC_EDIT_SET_CAPACITY_MIN_COOLING =
    'dc_edit/SET_CAPACITY_MIN_COOLING';
export const DC_EDIT_SET_CAPACITY_MAX_COOLING =
    'dc_edit/SET_CAPACITY_MAX_COOLING';
export const DC_EDIT_SET_CAPACITY_MAX_FLOOR_SPACE =
    'dc_edit/SET_CAPACITY_MAX_FLOOR_SPACE';
export const DC_EDIT_SET_CAPACITY_PREFERRED_INDUSTRIES =
    'dc_edit/SET_CAPACITY_PREFERRED_INDUSTRIES';
export const DC_EDIT_SET_CAPACITY_INDUSTRY_EXCLUSIONS =
    'dc_edit/SET_CAPACITY_INDUSTRY_EXCLUSIONS';
export const DC_EDIT_SET_CAPACITY_COUNTRY_EXCLUSIONS =
    'dc_edit/SET_CAPACITY_COUNTRY_EXCLUSIONS';
export const DC_EDIT_SET_CAPACITY_PREFERRED_BUYER_BUSINESS_SIZE =
    'dc_edit/SET_CAPACITY_PREFERRED_BUYER_BUSINESS_SIZE';
export const DC_EDIT_SET_CAPACITY_AVAIL_DATE =
    'dc_edit/SET_CAPACITY_AVAIL_DATE';
export const DC_EDIT_SET_CAPACITY_TERM = 'dc_edit/SET_CAPACITY_TERM';
// pricing
export const DC_EDIT_SET_PRICING_PRICE_PER_KWT =
    'dc_edit/SET_PRICING_PRICE_PER_KWT';
export const DC_EDIT_SET_PRICING_PRICE = 'dc_edit/SET_PRICING_PRICE';
export const DC_EDIT_SET_PRICING_FLOOR_SPACE =
    'dc_edit/SET_PRICING_FLOOR_SPACE';
export const DC_EDIT_SET_PRICING_FLOOR_SPACE_PRICE =
    'dc_edit/SET_PRICING_FLOOR_SPACE_PRICE';
export const DC_EDIT_SET_PRICING_CAGE = 'dc_edit/SET_PRICING_CAGE';
export const DC_EDIT_SET_PRICING_CAGE_PRICE = 'dc_edit/SET_PRICING_CAGE_PRICE';
export const DC_EDIT_SET_PRICING_RACK = 'dc_edit/SET_PRICING_RACK';
export const DC_EDIT_SET_PRICING_RACK_OR_CABINET_PRICE =
    'dc_edit/SET_PRICING_RACK_OR_CABINET_PRICE';
export const DC_EDIT_SET_PRICING_PRIVATE_SUITE =
    'dc_edit/SET_PRICING_PRIVATE_SUITE';
export const DC_EDIT_SET_PRICING_PRIVATE_SUITE_PRICE =
    'dc_edit/SET_PRICING_PRIVATE_SUITE_PRICE';
export const DC_EDIT_SET_PRICING_TIERED = 'dc_edit/SET_PRICING_TIERED';
export const DC_EDIT_SET_PRICING_NUMBER_OF_TIERS =
    'dc_edit/SET_PRICING_NUMBER_OF_TIERS';
export const DC_EDIT_SET_PRICING_PURCHASE_VOLUME =
    'dc_edit/SET_PRICING_PURCHASE_VOLUME';
export const DC_EDIT_SET_PRICING_CLIENT_BUSINESS_SIZE =
    'dc_edit/SET_PRICING_CLIENT_BUSINESS_SIZE';
export const DC_EDIT_SET_PRICING_TERM = 'dc_edit/SET_PRICING_TERM';
export const DC_EDIT_SET_PRICING_SLA = 'dc_edit/SET_PRICING_SLA';
export const DC_EDIT_SET_PRICING_CHOSEN_SLA =
    'dc_edit/SET_PRICING_STANDART_SLA';
export const DC_EDIT_SET_PRICING_CUSTOM_SLA_FILE =
    'dc_edit/SET_PRICING_CUSTOM_SLA_FILE';
export const DC_EDIT_SET_PRICING_LEASE_AGREEMENT =
    'dc_edit/SET_PRICING_LEASE_AGREEMENT';
export const DC_EDIT_SET_PURCHASE_FROM_1_TO_10K =
    'dc_edit/SET_PURCHASE_FROM_1_TO_10K';
export const DC_EDIT_SET_PURCHASE_FROM_101K_TO_1M =
    'dc_edit/SET_PURCHASE_FROM_101K_TO_1M';
export const DC_EDIT_SET_PURCHASE_GREATER_THAN_1M =
    'dc_edit/SET_PURCHASE_GREATER_THAN_1M';
export const DC_EDIT_SET_COMPANY_BUSINESS_SIZE_FROM_1_TO_10 =
    'dc_edit/SET_COMPANY_BUSINESS_SIZE_FROM_1_TO_10';
export const DC_EDIT_SET_COMPANY_BUSINESS_SIZE_FROM_101_TO_1000 =
    'dc_edit/SET_COMPANY_BUSINESS_SIZE_FROM_101_TO_1000';
export const DC_EDIT_SET_COMPANY_GREATER_THAN_1000 =
    'dc_edit/SET_COMPANY_GREATER_THAN_1000';
export const DC_EDIT_SET_TERMS_OF_LEASE_FROM_1_TO_3 =
    'dc_edit/SET_TERMS_OF_LEASE_FROM_1_TO_3';
export const DC_EDIT_SET_TERMS_OF_LEASE_FROM_3_TO_5 =
    'dc_edit/SET_TERMS_OF_LEASE_FROM_3_TO_5';
export const DC_EDIT_SET_TERMS_OF_LEASE_GREATER_THAN_5 =
    'dc_edit/SET_TERMS_OF_LEASE_GREATER_THAN_5';
